version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/var/www/html
        ports:
            - 8100:8100
            - 6100:6100
